remote_theme: nickbenn-workshop/just-the-docs

title: Is it a Perfect Square?

aux_links_new_tab: true
aux_links:
  Javadocs: "/api/"
  "Source repository": "https://github.com/nickbenn-workshop/is-perfect-square/"
#  Assignment:

